CREATE PROCEDURE [dbo].[FI_SP_ConsBeneficiario]
	@IdCliente BIGINT = 0
AS
BEGIN
	IF(ISNULL(@IdCliente,0) = 0)
		SELECT NOME, CPF, IDCLIENTE, ID FROM BENEFICIARIOS WITH(NOLOCK)
	ELSE
		SELECT NOME, CPF, IDCLIENTE, ID FROM BENEFICIARIOS WITH(NOLOCK) WHERE IDCliente = @IdCliente
END